# Build all projects.

pr: none      # Disable pull request triggers.
trigger: none


# Build.BuildNumber (see versioning.yml)
name: $(FileVersion).$(Year:yy)$(DayOfYear).$(Rev:r)

pool:
  name: Fluent-Blazor-1ESPT

extends:
  template: common/template-to-build-projects.yml
  parameters:
      Projects: |
       **/Microsoft.Fast.Components.FluentUI.csproj
       **/Microsoft.Fast.Components.FluentUI.Icons.csproj
       **/Microsoft.Fast.Components.FluentUI.Emojis.csproj
       **/Microsoft.Fast.Templates.FluentUI.csproj
       **/Microsoft.Fast.Components.FluentUI.DataGrid.EntityFrameworkAdapter.csproj
      Tests: |
       **/Microsoft.Fast.Components.FluentUI.Tests.csproj